import { useEffect, useState } from 'react';
import { AdminDataGrid } from '../components/AdminDataGrid';
import { AdminDialog } from '../components/AdminDialog';
import { createCourt, deleteCourt, getCourts, getVenues, updateCourt } from '../lib/api';
import type { Court, CourtPayload, Venue } from '../types';

const initial: CourtPayload = { name: '', venueId: 0, active: true };

export function AdminPlayingCourtsPage() {
  const [items, setItems] = useState<Court[]>([]); const [venues, setVenues] = useState<Venue[]>([]); const [form, setForm] = useState<CourtPayload>(initial); const [editing, setEditing] = useState<Court | null>(null); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [modalError, setModalError] = useState<string | null>(null);
  const load = () => getCourts().then(setItems).catch((reason: Error) => setError(reason.message));
  useEffect(() => { load(); getVenues().then(setVenues).catch((reason: Error) => setError(reason.message)); }, []);
  const close = (force = false) => { if (saving && !force) return; setOpen(false); setEditing(null); setForm(initial); setModalError(null); };
  const edit = (item: Court) => { setModalError(null); setEditing(item); setForm({ name: item.name, venueId: item.venueId, active: item.active }); setOpen(true); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setModalError(null); try { if (editing) await updateCourt(editing.id, form); else await createCourt(form); close(true); await load(); } catch (reason) { setModalError(reason instanceof Error ? reason.message : 'No se pudo guardar la cancha.'); } finally { setSaving(false); } };
  return <div className="admin-panel"><div className="panel-header"><div><p className="eyebrow">ABM</p><h1>Canchas</h1></div><button className="primary-button" onClick={() => { setForm(initial); setModalError(null); setOpen(true); }}>Agregar cancha</button></div><p className="field-hint">Cada cancha pertenece a una sede. Ejemplo: Cancha 1, Cancha 2.</p>{error && <div className="inline-state">{error}</div>}<section className="data-card"><AdminDataGrid rows={items} emptyMessage="No hay canchas cargadas. Primero crea una sede." columns={[{ label: 'Cancha', render: (item) => <strong>{item.name}</strong> }, { label: 'Sede', render: (item) => item.venue?.name ?? 'Sede no disponible' }, { label: 'Estado', render: (item) => <span className={`status-chip ${item.active ? 'status-live' : 'status-draft'}`}>{item.active ? 'Activa' : 'Inactiva'}</span> }]} renderActions={(item) => <><button className="inline-link" onClick={() => edit(item)}>Editar</button><button className="danger-link" onClick={async () => { if (!window.confirm(`Se eliminara ${item.name}.`)) return; try { await deleteCourt(item.id); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo eliminar la cancha.'); } }}>Eliminar</button></>} /></section>{open && <AdminDialog title={editing ? 'Editar cancha' : 'Nueva cancha'} onClose={close}><form className="editor-form" onSubmit={save}>{modalError && <div className="inline-state span-2">{modalError}</div>}<label>Nombre<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Cancha 1" required /></label><label>Sede<select value={form.venueId} onChange={(event) => setForm({ ...form, venueId: Number(event.target.value) })} required><option value="0">Seleccionar sede</option>{venues.filter((venue) => venue.active).map((venue) => <option key={venue.id} value={venue.id}>{venue.name}</option>)}</select></label><label className="checkbox-row span-2"><input type="checkbox" checked={form.active ?? true} onChange={(event) => setForm({ ...form, active: event.target.checked })} />Cancha activa</label><div className="span-2 form-actions"><button className="primary-button" disabled={saving}>{saving ? 'Guardando...' : 'Guardar cancha'}</button></div></form></AdminDialog>}</div>;
}
