import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { AdminDataGrid } from '../components/AdminDataGrid';
import { AdminDialog } from '../components/AdminDialog';
import { useAuth } from '../lib/auth';
import { addTournamentCategory, createTournamentZone, divideTournamentZones, getCategories, getCourts, getTournament, getTournamentScheduleGrid, updateTournamentCategory, updateTournamentScheduleSlot, updateTournamentZone } from '../lib/api';
import type { Category, Court, TournamentCategory, TournamentDetail, TournamentScheduleSlot, TournamentZone } from '../types';

type CategoryPayload = { categoryId: number; pointsPerSet: number; setsToWin: number; zoneSize: number };
type ZonePayload = { tournamentCategoryId: number; courtId: number; name: string; capacity: number };
const toInput = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : '';

export function AdminTournamentDetailPage() {
  const { user } = useAuth(); const { id } = useParams(); const tournamentId = Number(id); const director = user?.role === 'DIRECTOR';
  const [item, setItem] = useState<TournamentDetail | null>(null); const [categories, setCategories] = useState<Category[]>([]); const [courts, setCourts] = useState<Court[]>([]); const [slots, setSlots] = useState<TournamentScheduleSlot[]>([]); const [categoryEdit, setCategoryEdit] = useState<TournamentCategory | null>(null); const [zoneEdit, setZoneEdit] = useState<TournamentZone | null>(null); const [slotEdit, setSlotEdit] = useState<TournamentScheduleSlot | null>(null); const [categoryOpen, setCategoryOpen] = useState(false); const [zoneOpen, setZoneOpen] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = () => { getTournament(tournamentId).then(setItem).catch((e: Error) => setError(e.message)); if (director) getTournamentScheduleGrid(tournamentId).then(setSlots).catch((e: Error) => setError(e.message)); };
  useEffect(() => { load(); if (director) { getCategories().then(setCategories); getCourts().then(setCourts); } }, [tournamentId, director]);
  if (!item) return <div className="admin-panel inline-state">{error ?? 'Cargando torneo...'}</div>;
  return <div className="admin-panel"><div className="panel-header"><div><p className="eyebrow">Torneo</p><h1>{item.name}</h1></div><Link to="/app/torneos" className="secondary-button">Volver</Link></div>{error && <div className="inline-state">{error}</div>}
    <div className="panel-header"><h2>Categorias</h2>{director && <button className="primary-button" onClick={() => { setCategoryEdit(null); setCategoryOpen(true); }}>Agregar categoria</button>}</div><section className="data-card"><AdminDataGrid rows={item.categories} emptyMessage="No hay categorias configuradas." columns={[{ label: 'Categoria', render: (x) => <strong>{x.category.name}</strong> }, { label: 'Formato', render: (x) => `${x.setsToWin} set · ${x.pointsPerSet} tantos` }, { label: 'Zona', render: (x) => `${x.zoneSize} parejas` }]} renderActions={(x) => director ? <><button className="inline-link" onClick={() => { setCategoryEdit(x); setCategoryOpen(true); }}>Editar</button><button className="inline-link" onClick={async () => { try { await divideTournamentZones(x.id); load(); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudieron dividir las zonas.'); } }}>Dividir zonas</button></> : <span>-</span>} /></section>
    <div className="panel-header"><div><h2>Grilla macro</h2><p className="field-hint">16 partidos previstos por categoria, intercalando las cuatro zonas. La cancha se toma de cada zona.</p></div></div><section className="data-card"><AdminDataGrid rows={slots} emptyMessage="Agrega una categoria para crear la grilla." columns={[{ label: '#', render: (x) => x.sequence }, { label: 'Categoria', render: (x) => x.tournamentCategory.category.name }, { label: 'Partido', render: (x) => `${x.zoneName} · P${x.matchOrder}` }, { label: 'Cancha', render: (x) => x.court?.name ?? 'A definir' }, { label: 'Horario', render: (x) => x.scheduledAt ? new Intl.DateTimeFormat('es-AR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(x.scheduledAt)) : 'A definir' }]} renderActions={(x) => director ? <button className="inline-link" onClick={() => setSlotEdit(x)}>Horario</button> : <span>-</span>} /></section>
    <div className="panel-header"><h2>Zonas</h2>{director && <button className="primary-button" onClick={() => { setZoneEdit(null); setZoneOpen(true); }}>Agregar zona</button>}</div><section className="data-card"><AdminDataGrid rows={item.zones} emptyMessage="Usa Dividir zonas para crear las zonas con las parejas confirmadas." columns={[{ label: 'Zona', render: (x) => <strong>{x.name}</strong> }, { label: 'Categoria', render: (x) => x.tournamentCategory.category.name }, { label: 'Cancha', render: (x) => x.court.name }, { label: 'Cupo', render: (x) => x.capacity }]} renderActions={(x) => <>{director && <button className="inline-link" onClick={() => { setZoneEdit(x); setZoneOpen(true); }}>Editar</button>}<Link className="inline-link" to={`/app/zonas/${x.id}`}>Partidos</Link></>} /></section>
    {categoryOpen && <AdminDialog title="Categoria" onClose={() => setCategoryOpen(false)}><CategoryForm categories={categories} editing={categoryEdit} onSave={async (v) => { if (categoryEdit) await updateTournamentCategory(categoryEdit.id, v); else await addTournamentCategory(tournamentId, v); setCategoryOpen(false); load(); }} /></AdminDialog>}{zoneOpen && <AdminDialog title="Zona" onClose={() => setZoneOpen(false)}><ZoneForm categories={item.categories} courts={courts} editing={zoneEdit} onSave={async (v) => { if (zoneEdit) await updateTournamentZone(zoneEdit.id, v); else await createTournamentZone(v); setZoneOpen(false); load(); }} /></AdminDialog>}{slotEdit && <AdminDialog title="Horario previsto" onClose={() => setSlotEdit(null)}><form className="editor-form" onSubmit={async (e) => { e.preventDefault(); const field = new FormData(e.currentTarget).get('scheduledAt') as string; await updateTournamentScheduleSlot(slotEdit.id, { scheduledAt: field ? new Date(field).toISOString() : null }); setSlotEdit(null); load(); }}><label className="span-2">Fecha y hora<input name="scheduledAt" type="datetime-local" defaultValue={toInput(slotEdit.scheduledAt)} /></label><div className="span-2 form-actions"><button className="primary-button">Guardar</button></div></form></AdminDialog>}
  </div>;
}
function CategoryForm({ categories, editing, onSave }: { categories: Category[]; editing: TournamentCategory | null; onSave: (v: CategoryPayload) => Promise<void> }) { const [v, setV] = useState<CategoryPayload>({ categoryId: editing?.categoryId ?? 0, pointsPerSet: editing?.pointsPerSet ?? 25, setsToWin: editing?.setsToWin ?? 1, zoneSize: editing?.zoneSize ?? 4 }); return <form className="editor-form" onSubmit={(e) => { e.preventDefault(); onSave(v); }}><label className="span-2">Categoria<select value={v.categoryId} disabled={!!editing} onChange={(e) => setV({ ...v, categoryId: Number(e.target.value) })}><option value="0">Seleccionar</option>{categories.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Tantos<input type="number" value={v.pointsPerSet} onChange={(e) => setV({ ...v, pointsPerSet: Number(e.target.value) })} /></label><label>Sets<input type="number" value={v.setsToWin} onChange={(e) => setV({ ...v, setsToWin: Number(e.target.value) })} /></label><label className="span-2">Parejas por zona<select value={v.zoneSize} onChange={(e) => setV({ ...v, zoneSize: Number(e.target.value) })}><option value="3">3</option><option value="4">4</option></select></label><div className="span-2 form-actions"><button className="primary-button">Guardar</button></div></form>; }
function ZoneForm({ categories, courts, editing, onSave }: { categories: TournamentDetail['categories']; courts: Court[]; editing: TournamentZone | null; onSave: (v: ZonePayload) => Promise<void> }) { const [v, setV] = useState<ZonePayload>({ tournamentCategoryId: editing?.tournamentCategoryId ?? 0, courtId: editing?.court.id ?? 0, name: editing?.name ?? '', capacity: editing?.capacity ?? 4 }); return <form className="editor-form" onSubmit={(e) => { e.preventDefault(); onSave(v); }}><label>Nombre<input value={v.name} onChange={(e) => setV({ ...v, name: e.target.value })} required /></label><label>Cancha<select value={v.courtId} onChange={(e) => setV({ ...v, courtId: Number(e.target.value) })} required><option value="0">Seleccionar</option>{courts.filter((x) => x.active).map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Categoria<select value={v.tournamentCategoryId} disabled={!!editing} onChange={(e) => setV({ ...v, tournamentCategoryId: Number(e.target.value) })} required><option value="0">Seleccionar</option>{categories.map((x) => <option key={x.id} value={x.id}>{x.category.name}</option>)}</select></label><label>Cupo<input type="number" value={v.capacity} onChange={(e) => setV({ ...v, capacity: Number(e.target.value) })} /></label><div className="span-2 form-actions"><button className="primary-button">Guardar zona</button></div></form>; }
