import { useEffect, useState } from 'react';
import { AdminDataGrid } from '../components/AdminDataGrid';
import { getCourts, getTournamentScheduleGrid, getTournaments, updateTournamentScheduleSlot } from '../lib/api';
import type { Court, Tournament, TournamentScheduleSlot } from '../types';

type ProgramTab = 'matches' | 'venues' | 'categories';
const bySchedule = (left: TournamentScheduleSlot, right: TournamentScheduleSlot) => (left.scheduledAt ?? '9999').localeCompare(right.scheduledAt ?? '9999') || left.sequence - right.sequence;
const venueName = (slot: TournamentScheduleSlot) => slot.court?.venue?.name ?? 'Sede a definir';
const matchLabel = (slot: TournamentScheduleSlot, allSlots: TournamentScheduleSlot[]) => {
  if (slot.stage === 'QUARTERFINAL') return `Cuartos ${slot.matchOrder}`;
  if (slot.stage === 'SEMIFINAL') return `Semifinal ${slot.matchOrder}`;
  if (slot.stage === 'FINAL') return 'Final';
  if (slot.matchOrder < 3) return slot.matchOrder === 1 ? '1 vs 2' : '3 vs 4';
  const source = (order: number) => allSlots.find((candidate) => candidate.tournamentCategoryId === slot.tournamentCategoryId && candidate.zoneName === slot.zoneName && candidate.stage === 'ZONE' && candidate.matchOrder === order)?.sequence ?? '?';
  return slot.matchOrder === 3 ? `G Partido ${source(1)} vs P Partido ${source(2)}` : `G Partido ${source(2)} vs P Partido ${source(1)}`;
};

export function AdminProgramPage() {
  const [tournaments, setTournaments] = useState<Tournament[]>([]); const [courts, setCourts] = useState<Court[]>([]); const [tournamentId, setTournamentId] = useState(0); const [slots, setSlots] = useState<TournamentScheduleSlot[]>([]); const [tab, setTab] = useState<ProgramTab>('matches'); const [venueTab, setVenueTab] = useState(''); const [categoryTab, setCategoryTab] = useState(''); const [error, setError] = useState<string | null>(null);
  const load = () => { if (tournamentId) getTournamentScheduleGrid(tournamentId).then(setSlots).catch((reason: Error) => setError(reason.message)); };
  useEffect(() => { getTournaments().then((items) => { setTournaments(items); setTournamentId(items[0]?.id ?? 0); }).catch((reason: Error) => setError(reason.message)); getCourts().then(setCourts).catch((reason: Error) => setError(reason.message)); }, []);
  useEffect(() => { if (!tournamentId) { setSlots([]); return; } load(); }, [tournamentId]);
  const assignCourt = async (slot: TournamentScheduleSlot, courtId: number) => { try { await updateTournamentScheduleSlot(slot.id, { courtId: courtId || null }); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo asignar la cancha.'); } };
  const columns = [{ label: 'Partido', render: (slot: TournamentScheduleSlot) => slot.sequence }, { label: 'Categoria', render: (slot: TournamentScheduleSlot) => slot.tournamentCategory.category.name }, { label: 'Zona / Etapa', render: (slot: TournamentScheduleSlot) => slot.zoneName }, { label: 'Cruce', render: (slot: TournamentScheduleSlot) => matchLabel(slot, slots) }, { label: 'Cancha / Sede', render: (slot: TournamentScheduleSlot) => <select aria-label={`Cancha para partido ${slot.sequence}`} value={slot.courtId ?? 0} onChange={(event) => assignCourt(slot, Number(event.target.value))}><option value="0">Sin asignar</option>{courts.filter((court) => court.active).map((court) => <option key={court.id} value={court.id}>{court.venue?.name ? `${court.venue.name} - ${court.name}` : court.name}</option>)}</select> }, { label: 'Horario', render: (slot: TournamentScheduleSlot) => slot.scheduledAt ? new Intl.DateTimeFormat('es-AR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(slot.scheduledAt)) : 'A definir' }];
  const byVenue = slots.reduce<Record<string, TournamentScheduleSlot[]>>((groups, slot) => { const venue = venueName(slot); (groups[venue] ??= []).push(slot); return groups; }, {});
  const byCategory = slots.reduce<Record<string, Record<string, TournamentScheduleSlot[]>>>((groups, slot) => { const category = slot.tournamentCategory.category.name; const section = slot.stage === 'ZONE' ? slot.zoneName : slot.zoneName; (groups[category] ??= {}); (groups[category][section] ??= []).push(slot); return groups; }, {});
  const venueNames = Object.keys(byVenue).sort(); const categoryNames = Object.keys(byCategory).sort(); const selectedVenue = venueNames.includes(venueTab) ? venueTab : venueNames[0]; const selectedCategory = categoryNames.includes(categoryTab) ? categoryTab : categoryNames[0];
  return <div className="admin-panel"><div className="panel-header"><div><p className="eyebrow">Organizacion</p><h1>Programa</h1><p className="field-hint">Cambia la cancha de cada partido desde cualquier vista.</p></div></div><section className="data-card"><label>Seleccionar torneo<select value={tournamentId} onChange={(event) => { setTournamentId(Number(event.target.value)); setVenueTab(''); setCategoryTab(''); }}><option value="0">Seleccionar torneo</option>{tournaments.map((tournament) => <option key={tournament.id} value={tournament.id}>{tournament.name}</option>)}</select></label></section>{error && <div className="inline-state">{error}</div>}<div className="program-tabs" role="tablist" aria-label="Vistas del programa"><button type="button" className={tab === 'matches' ? 'is-selected' : ''} onClick={() => setTab('matches')}>Partidos</button><button type="button" className={tab === 'venues' ? 'is-selected' : ''} onClick={() => setTab('venues')}>Sedes</button><button type="button" className={tab === 'categories' ? 'is-selected' : ''} onClick={() => setTab('categories')}>Categorias</button></div>{tab === 'matches' && <ProgramTable title="Todos los partidos" slots={[...slots].sort((left, right) => left.sequence - right.sequence)} columns={columns} />}{tab === 'venues' && <ProgramSubTabs labels={venueNames} selected={selectedVenue} onSelect={setVenueTab} ariaLabel="Sedes del programa">{selectedVenue && <ProgramTable title={selectedVenue} slots={[...byVenue[selectedVenue]].sort(bySchedule)} columns={columns} />}</ProgramSubTabs>}{tab === 'categories' && <ProgramSubTabs labels={categoryNames} selected={selectedCategory} onSelect={setCategoryTab} ariaLabel="Categorias del programa">{selectedCategory && <section className="data-card"><div className="panel-header"><h2>{selectedCategory}</h2></div>{Object.entries(byCategory[selectedCategory]).sort(([left], [right]) => left.localeCompare(right)).map(([section, sectionSlots]) => <div className="program-zone" key={section}><h3>{section}</h3><AdminDataGrid rows={[...sectionSlots].sort(bySchedule)} emptyMessage="No hay partidos previstos." columns={columns} /></div>)}</section>}</ProgramSubTabs>}{tournamentId > 0 && !slots.length && <div className="inline-state">Agrega categorias y zonas al torneo para generar el programa.</div>}</div>;
}

function ProgramTable({ title, slots, columns }: { title: string; slots: TournamentScheduleSlot[]; columns: { label: string; render: (slot: TournamentScheduleSlot) => React.ReactNode }[] }) { return <section className="data-card"><div className="panel-header"><h2>{title}</h2></div><AdminDataGrid rows={slots} emptyMessage="No hay partidos previstos." columns={columns} /></section>; }
function ProgramSubTabs({ labels, selected, onSelect, ariaLabel, children }: { labels: string[]; selected: string | undefined; onSelect: (label: string) => void; ariaLabel: string; children: React.ReactNode }) { if (!labels.length) return <div className="inline-state">No hay partidos configurados todavia.</div>; return <><div className="program-subtabs" role="tablist" aria-label={ariaLabel}>{labels.map((label) => <button type="button" key={label} className={selected === label ? 'is-selected' : ''} onClick={() => onSelect(label)}>{label}</button>)}</div>{children}</>; }
