import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { AdminDataGrid } from '../components/AdminDataGrid';
import { AdminDialog } from '../components/AdminDialog';
import { createTournament, getTournaments, updateTournament } from '../lib/api';
import type { Tournament, TournamentPayload } from '../types';

const initial: TournamentPayload = { name: '', feePerPlayer: 15000, startsAt: '', endsAt: '', playingDays: [], city: 'Ciudad de Buenos Aires', status: 'DRAFT' };
const money = new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 });
const statusLabel = (status: Tournament['status']) => status === 'DRAFT' ? 'Borrador' : status === 'ACTIVE' ? 'Activo' : 'Finalizado';

export function AdminTournamentsPage() {
  const [items, setItems] = useState<Tournament[]>([]); const [form, setForm] = useState<TournamentPayload>(initial); const [editing, setEditing] = useState<Tournament | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = () => getTournaments().then(setItems).catch((reason: Error) => setError(reason.message)); useEffect(() => { load(); }, []);
  const close = () => { setOpen(false); setEditing(null); setForm(initial); };
  const edit = (item: Tournament) => { setEditing(item); setForm({ name: item.name, feePerPlayer: item.feePerPlayer, startsAt: item.startsAt ?? '', endsAt: item.endsAt ?? '', playingDays: item.playingDays ?? [], city: item.city ?? '', status: item.status }); setOpen(true); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); try { if (editing) await updateTournament(editing.id, form); else await createTournament(form); close(); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No se pudo guardar el torneo.'); } };
  return <div className="admin-panel"><div className="panel-header"><div><p className="eyebrow">Competencia</p><h1>Torneos</h1></div><button className="primary-button" onClick={() => { setForm(initial); setOpen(true); }}>Nuevo torneo</button></div>{error && <div className="inline-state">{error}</div>}<section className="data-card"><AdminDataGrid rows={items} emptyMessage="No hay torneos cargados." columns={[{ label: 'Torneo', render: (item) => <strong>{item.name}</strong> }, { label: 'Tarifa por jugadora', render: (item) => money.format(item.feePerPlayer) }, { label: 'Fechas', render: (item) => item.startsAt ? `${item.startsAt}${item.endsAt ? ` al ${item.endsAt}` : ''}` : '-' }, { label: 'Sede', render: (item) => item.city ?? '-' }, { label: 'Estado', render: (item) => <span className={`status-chip ${item.status === 'ACTIVE' ? 'status-live' : 'status-draft'}`}>{statusLabel(item.status)}</span> }]} renderActions={(item) => <><button type="button" className="inline-link" onClick={() => edit(item)}>Editar</button><Link className="inline-link" to={`/app/torneos/${item.id}`}>Abrir</Link></>} /></section>{open && <AdminDialog title={editing ? 'Editar torneo' : 'Nuevo torneo'} onClose={close}><form className="editor-form" onSubmit={save}><label className="span-2">Nombre<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label>Tarifa por jugadora<input type="number" min="0" step="1" value={form.feePerPlayer ?? 15000} onChange={(event) => setForm({ ...form, feePerPlayer: Number(event.target.value) })} required /></label><label>Estado<select value={form.status ?? 'DRAFT'} onChange={(event) => setForm({ ...form, status: event.target.value as TournamentPayload['status'] })}><option value="DRAFT">Borrador</option><option value="ACTIVE">Activo</option><option value="COMPLETED">Finalizado</option></select></label><label>Inicio<input type="date" value={form.startsAt ?? ''} onChange={(event) => setForm({ ...form, startsAt: event.target.value })} /></label><label>Fin<input type="date" value={form.endsAt ?? ''} onChange={(event) => setForm({ ...form, endsAt: event.target.value })} /></label><label className="span-2">Dias de juego<input type="text" value={(form.playingDays ?? []).join(', ')} onChange={(event) => setForm({ ...form, playingDays: event.target.value.split(',').map((value) => value.trim()).filter(Boolean) })} placeholder="2026-11-21, 2026-11-22" /></label><small className="field-hint span-2">Ingresar las fechas separadas por coma. El Programa usara estos dias junto con el horario y cupo de cada sede.</small><label className="span-2">Ciudad<input value={form.city ?? ''} onChange={(event) => setForm({ ...form, city: event.target.value })} /></label><div className="span-2 form-actions"><button className="primary-button">{editing ? 'Guardar cambios' : 'Crear torneo'}</button></div></form></AdminDialog>}</div>;
}
