import { useEffect, useState } from 'react';
import { AdminDataGrid } from '../components/AdminDataGrid';
import { getTournamentScheduleGrid, getTournaments } from '../lib/api';
import type { Tournament, TournamentScheduleSlot } from '../types';

export function AdminProgramPage() {
  const [tournaments, setTournaments] = useState<Tournament[]>([]); const [tournamentId, setTournamentId] = useState(0); const [slots, setSlots] = useState<TournamentScheduleSlot[]>([]); const [error, setError] = useState<string | null>(null);
  useEffect(() => { getTournaments().then((items) => { setTournaments(items); setTournamentId(items[0]?.id ?? 0); }).catch((reason: Error) => setError(reason.message)); }, []);
  useEffect(() => { if (!tournamentId) { setSlots([]); return; } getTournamentScheduleGrid(tournamentId).then(setSlots).catch((reason: Error) => setError(reason.message)); }, [tournamentId]);
  const byVenue = slots.reduce<Record<string, TournamentScheduleSlot[]>>((groups, slot) => { const venue = slot.court?.venue?.name ?? slot.court?.name ?? 'Sede a definir'; (groups[venue] ??= []).push(slot); return groups; }, {});
  return <div className="admin-panel"><div className="panel-header"><div><p className="eyebrow">Organizacion</p><h1>Programa</h1><p className="field-hint">Partidos previstos por sede. Los equipos se reemplazaran al confirmar las zonas.</p></div></div><section className="data-card"><label>Seleccionar torneo<select value={tournamentId} onChange={(event) => setTournamentId(Number(event.target.value))}><option value="0">Seleccionar torneo</option>{tournaments.map((tournament) => <option key={tournament.id} value={tournament.id}>{tournament.name}</option>)}</select></label></section>{error && <div className="inline-state">{error}</div>}{Object.entries(byVenue).map(([venue, venueSlots]) => <section className="data-card" key={venue}><div className="panel-header"><h2>{venue}</h2></div><AdminDataGrid rows={venueSlots} emptyMessage="No hay partidos previstos." columns={[{ label: 'Partido', render: (slot) => slot.sequence }, { label: 'Categoria', render: (slot) => slot.tournamentCategory.category.name }, { label: 'Zona', render: (slot) => slot.zoneName }, { label: 'Cruce', render: (slot) => `Partido ${slot.matchOrder}: Equipo 1 vs Equipo 2` }, { label: 'Horario', render: (slot) => slot.scheduledAt ? new Intl.DateTimeFormat('es-AR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(slot.scheduledAt)) : 'A definir' }]} /></section>)}{tournamentId > 0 && !slots.length && <div className="inline-state">Agrega categorias y zonas al torneo para generar el programa.</div>}</div>;
}
